// Generated by gencpp from file denso_robot_core/MoveStringActionGoal.msg
// DO NOT EDIT!


#ifndef DENSO_ROBOT_CORE_MESSAGE_MOVESTRINGACTIONGOAL_H
#define DENSO_ROBOT_CORE_MESSAGE_MOVESTRINGACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <denso_robot_core/MoveStringGoal.h>

namespace denso_robot_core
{
template <class ContainerAllocator>
struct MoveStringActionGoal_
{
  typedef MoveStringActionGoal_<ContainerAllocator> Type;

  MoveStringActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  MoveStringActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::denso_robot_core::MoveStringGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveStringActionGoal_

typedef ::denso_robot_core::MoveStringActionGoal_<std::allocator<void> > MoveStringActionGoal;

typedef boost::shared_ptr< ::denso_robot_core::MoveStringActionGoal > MoveStringActionGoalPtr;
typedef boost::shared_ptr< ::denso_robot_core::MoveStringActionGoal const> MoveStringActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator1> & lhs, const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator1> & lhs, const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace denso_robot_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d5162e2fbd42316c195207bf83024d9";
  }

  static const char* value(const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d5162e2fbd42316ULL;
  static const uint64_t static_value2 = 0xc195207bf83024d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "denso_robot_core/MoveStringActionGoal";
  }

  static const char* value(const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"MoveStringGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: denso_robot_core/MoveStringGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32  comp\n"
"string pose\n"
"string option\n"
;
  }

  static const char* value(const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveStringActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::denso_robot_core::MoveStringActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::denso_robot_core::MoveStringGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DENSO_ROBOT_CORE_MESSAGE_MOVESTRINGACTIONGOAL_H
