add_post_pro_depowdering:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: &loop_hz 125
    
  arm_controller:
    state_publish_rate: 50
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    gains:
      joint_1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

  gripper_controller:
    state_publish_rate: 50
    type: effort_controllers/JointTrajectoryController
    joints:
      - gripper_Joint
    gains:
      gripper_Joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

controller_list:
  - name: "/add_post_pro_depowdering/arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  - name: "/add_post_pro_depowdering/gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - gripper_Joint