; Auto-generated. Do not edit!


(cl:in-package denso_robot_core-msg)


;//! \htmlinclude DriveStringGoal.msg.html

(cl:defclass <DriveStringGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type cl:string
    :initform "")
   (option
    :reader option
    :initarg :option
    :type cl:string
    :initform ""))
)

(cl:defclass DriveStringGoal (<DriveStringGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveStringGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveStringGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name denso_robot_core-msg:<DriveStringGoal> is deprecated: use denso_robot_core-msg:DriveStringGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <DriveStringGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_robot_core-msg:pose-val is deprecated.  Use denso_robot_core-msg:pose instead.")
  (pose m))

(cl:ensure-generic-function 'option-val :lambda-list '(m))
(cl:defmethod option-val ((m <DriveStringGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_robot_core-msg:option-val is deprecated.  Use denso_robot_core-msg:option instead.")
  (option m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveStringGoal>) ostream)
  "Serializes a message object of type '<DriveStringGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'pose))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'option))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'option))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveStringGoal>) istream)
  "Deserializes a message object of type '<DriveStringGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'pose) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'pose) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'option) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'option) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveStringGoal>)))
  "Returns string type for a message object of type '<DriveStringGoal>"
  "denso_robot_core/DriveStringGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveStringGoal)))
  "Returns string type for a message object of type 'DriveStringGoal"
  "denso_robot_core/DriveStringGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveStringGoal>)))
  "Returns md5sum for a message object of type '<DriveStringGoal>"
  "9de8d255efc68542d1bc35e67afbfca4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveStringGoal)))
  "Returns md5sum for a message object of type 'DriveStringGoal"
  "9de8d255efc68542d1bc35e67afbfca4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveStringGoal>)))
  "Returns full string definition for message of type '<DriveStringGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string pose~%string option~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveStringGoal)))
  "Returns full string definition for message of type 'DriveStringGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string pose~%string option~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveStringGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'pose))
     4 (cl:length (cl:slot-value msg 'option))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveStringGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveStringGoal
    (cl:cons ':pose (pose msg))
    (cl:cons ':option (option msg))
))
