; Auto-generated. Do not edit!


(cl:in-package denso_robot_core-msg)


;//! \htmlinclude MoveStringResult.msg.html

(cl:defclass <MoveStringResult> (roslisp-msg-protocol:ros-message)
  ((HRESULT
    :reader HRESULT
    :initarg :HRESULT
    :type cl:integer
    :initform 0))
)

(cl:defclass MoveStringResult (<MoveStringResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveStringResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveStringResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name denso_robot_core-msg:<MoveStringResult> is deprecated: use denso_robot_core-msg:MoveStringResult instead.")))

(cl:ensure-generic-function 'HRESULT-val :lambda-list '(m))
(cl:defmethod HRESULT-val ((m <MoveStringResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader denso_robot_core-msg:HRESULT-val is deprecated.  Use denso_robot_core-msg:HRESULT instead.")
  (HRESULT m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveStringResult>) ostream)
  "Serializes a message object of type '<MoveStringResult>"
  (cl:let* ((signed (cl:slot-value msg 'HRESULT)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveStringResult>) istream)
  "Deserializes a message object of type '<MoveStringResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'HRESULT) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveStringResult>)))
  "Returns string type for a message object of type '<MoveStringResult>"
  "denso_robot_core/MoveStringResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveStringResult)))
  "Returns string type for a message object of type 'MoveStringResult"
  "denso_robot_core/MoveStringResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveStringResult>)))
  "Returns md5sum for a message object of type '<MoveStringResult>"
  "0e844160689200392730e0ad31896226")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveStringResult)))
  "Returns md5sum for a message object of type 'MoveStringResult"
  "0e844160689200392730e0ad31896226")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveStringResult>)))
  "Returns full string definition for message of type '<MoveStringResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 HRESULT~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveStringResult)))
  "Returns full string definition for message of type 'MoveStringResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 HRESULT~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveStringResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveStringResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveStringResult
    (cl:cons ':HRESULT (HRESULT msg))
))
