controller_list:
  - name: fake_Arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_Table_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_Gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - wire_joint
initial:  # Define initial robot poses per group
  - group: Arm
    pose: home
  - group: Gripper
    pose: open