# controller_manager_ns: controller_manager
# controller_list:
#   - name: add_post_pro_robot/arm_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

#   - name: add_post_pro_robot/turntable_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints: [turntable_revolve_joint]

add_post_pro_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  

  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

 

  # gripper_controller:
  #   type: "position_controllers/JointTrajectoryController"
  #   joints:
  #     - wire_joint
