// Generated by gencpp from file micro_epsilon_scancontrol_msgs/GetFeatureRequest.msg
// DO NOT EDIT!


#ifndef MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETFEATUREREQUEST_H
#define MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETFEATUREREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace micro_epsilon_scancontrol_msgs
{
template <class ContainerAllocator>
struct GetFeatureRequest_
{
  typedef GetFeatureRequest_<ContainerAllocator> Type;

  GetFeatureRequest_()
    : setting(0)  {
    }
  GetFeatureRequest_(const ContainerAllocator& _alloc)
    : setting(0)  {
  (void)_alloc;
    }



   typedef uint32_t _setting_type;
  _setting_type setting;





  typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFeatureRequest_

typedef ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<std::allocator<void> > GetFeatureRequest;

typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest > GetFeatureRequestPtr;
typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest const> GetFeatureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator1> & lhs, const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator2> & rhs)
{
  return lhs.setting == rhs.setting;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator1> & lhs, const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace micro_epsilon_scancontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "340dffc55dcd5acf86424b2679b5cac5";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x340dffc55dcd5acfULL;
  static const uint64_t static_value2 = 0x86424b2679b5cac5ULL;
};

template<class ContainerAllocator>
struct DataType< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micro_epsilon_scancontrol_msgs/GetFeatureRequest";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 setting\n"
;
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFeatureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::micro_epsilon_scancontrol_msgs::GetFeatureRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "setting: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.setting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETFEATUREREQUEST_H
