// Generated by gencpp from file micro_epsilon_scancontrol_msgs/GetResolutionRequest.msg
// DO NOT EDIT!


#ifndef MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETRESOLUTIONREQUEST_H
#define MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETRESOLUTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace micro_epsilon_scancontrol_msgs
{
template <class ContainerAllocator>
struct GetResolutionRequest_
{
  typedef GetResolutionRequest_<ContainerAllocator> Type;

  GetResolutionRequest_()
    {
    }
  GetResolutionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetResolutionRequest_

typedef ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<std::allocator<void> > GetResolutionRequest;

typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest > GetResolutionRequestPtr;
typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest const> GetResolutionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace micro_epsilon_scancontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micro_epsilon_scancontrol_msgs/GetResolutionRequest";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetResolutionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETRESOLUTIONREQUEST_H
