// Generated by gencpp from file micro_epsilon_scancontrol_msgs/GetResolution.msg
// DO NOT EDIT!


#ifndef MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETRESOLUTION_H
#define MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETRESOLUTION_H

#include <ros/service_traits.h>


#include <micro_epsilon_scancontrol_msgs/GetResolutionRequest.h>
#include <micro_epsilon_scancontrol_msgs/GetResolutionResponse.h>


namespace micro_epsilon_scancontrol_msgs
{

struct GetResolution
{

typedef GetResolutionRequest Request;
typedef GetResolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetResolution
} // namespace micro_epsilon_scancontrol_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolution > {
  static const char* value()
  {
    return "b29e2945c59c53f7e032bc7769074912";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolution&) { return value(); }
};

template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::GetResolution > {
  static const char* value()
  {
    return "micro_epsilon_scancontrol_msgs/GetResolution";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolution&) { return value(); }
};


// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest> should match
// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolution >
template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest> should match
// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::GetResolution >
template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::GetResolutionRequest>
{
  static const char* value()
  {
    return DataType< ::micro_epsilon_scancontrol_msgs::GetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolutionResponse> should match
// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolution >
template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::micro_epsilon_scancontrol_msgs::GetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::GetResolutionResponse> should match
// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::GetResolution >
template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::GetResolutionResponse>
{
  static const char* value()
  {
    return DataType< ::micro_epsilon_scancontrol_msgs::GetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::GetResolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_GETRESOLUTION_H
