// Generated by gencpp from file micro_epsilon_scancontrol_msgs/SetFeatureResponse.msg
// DO NOT EDIT!


#ifndef MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETFEATURERESPONSE_H
#define MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETFEATURERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace micro_epsilon_scancontrol_msgs
{
template <class ContainerAllocator>
struct SetFeatureResponse_
{
  typedef SetFeatureResponse_<ContainerAllocator> Type;

  SetFeatureResponse_()
    : return_code(0)  {
    }
  SetFeatureResponse_(const ContainerAllocator& _alloc)
    : return_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _return_code_type;
  _return_code_type return_code;





  typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetFeatureResponse_

typedef ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<std::allocator<void> > SetFeatureResponse;

typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse > SetFeatureResponsePtr;
typedef boost::shared_ptr< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse const> SetFeatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator1> & lhs, const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.return_code == rhs.return_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator1> & lhs, const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace micro_epsilon_scancontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c285fc637ab43abc6f59f97aab55a3bb";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc285fc637ab43abcULL;
  static const uint64_t static_value2 = 0x6f59f97aab55a3bbULL;
};

template<class ContainerAllocator>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "micro_epsilon_scancontrol_msgs/SetFeatureResponse";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 return_code\n"
;
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFeatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "return_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.return_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETFEATURERESPONSE_H
