// Generated by gencpp from file micro_epsilon_scancontrol_msgs/SetFeature.msg
// DO NOT EDIT!


#ifndef MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETFEATURE_H
#define MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETFEATURE_H

#include <ros/service_traits.h>


#include <micro_epsilon_scancontrol_msgs/SetFeatureRequest.h>
#include <micro_epsilon_scancontrol_msgs/SetFeatureResponse.h>


namespace micro_epsilon_scancontrol_msgs
{

struct SetFeature
{

typedef SetFeatureRequest Request;
typedef SetFeatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFeature
} // namespace micro_epsilon_scancontrol_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeature > {
  static const char* value()
  {
    return "b6319c48811935bafcd8759d2c550c8f";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeature&) { return value(); }
};

template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetFeature > {
  static const char* value()
  {
    return "micro_epsilon_scancontrol_msgs/SetFeature";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeature&) { return value(); }
};


// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeatureRequest> should match
// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeature >
template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeature >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetFeatureRequest> should match
// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetFeature >
template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetFeatureRequest>
{
  static const char* value()
  {
    return DataType< ::micro_epsilon_scancontrol_msgs::SetFeature >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse> should match
// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeature >
template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::micro_epsilon_scancontrol_msgs::SetFeature >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse> should match
// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetFeature >
template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetFeatureResponse>
{
  static const char* value()
  {
    return DataType< ::micro_epsilon_scancontrol_msgs::SetFeature >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetFeatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETFEATURE_H
