// Generated by gencpp from file micro_epsilon_scancontrol_msgs/SetResolution.msg
// DO NOT EDIT!


#ifndef MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETRESOLUTION_H
#define MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETRESOLUTION_H

#include <ros/service_traits.h>


#include <micro_epsilon_scancontrol_msgs/SetResolutionRequest.h>
#include <micro_epsilon_scancontrol_msgs/SetResolutionResponse.h>


namespace micro_epsilon_scancontrol_msgs
{

struct SetResolution
{

typedef SetResolutionRequest Request;
typedef SetResolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetResolution
} // namespace micro_epsilon_scancontrol_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolution > {
  static const char* value()
  {
    return "31b37757a8d3cae8da33ee6b9ff1b953";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetResolution&) { return value(); }
};

template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetResolution > {
  static const char* value()
  {
    return "micro_epsilon_scancontrol_msgs/SetResolution";
  }

  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetResolution&) { return value(); }
};


// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolutionRequest> should match
// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolution >
template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetResolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetResolutionRequest> should match
// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetResolution >
template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetResolutionRequest>
{
  static const char* value()
  {
    return DataType< ::micro_epsilon_scancontrol_msgs::SetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetResolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolutionResponse> should match
// service_traits::MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolution >
template<>
struct MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::micro_epsilon_scancontrol_msgs::SetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetResolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetResolutionResponse> should match
// service_traits::DataType< ::micro_epsilon_scancontrol_msgs::SetResolution >
template<>
struct DataType< ::micro_epsilon_scancontrol_msgs::SetResolutionResponse>
{
  static const char* value()
  {
    return DataType< ::micro_epsilon_scancontrol_msgs::SetResolution >::value();
  }
  static const char* value(const ::micro_epsilon_scancontrol_msgs::SetResolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICRO_EPSILON_SCANCONTROL_MSGS_MESSAGE_SETRESOLUTION_H
