// Auto-generated. Do not edit!

// (in-package denso_robot_core.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let PoseData = require('./PoseData.js');

//-----------------------------------------------------------

class MoveValueGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.comp = null;
      this.pose = null;
      this.option = null;
    }
    else {
      if (initObj.hasOwnProperty('comp')) {
        this.comp = initObj.comp
      }
      else {
        this.comp = 0;
      }
      if (initObj.hasOwnProperty('pose')) {
        this.pose = initObj.pose
      }
      else {
        this.pose = new PoseData();
      }
      if (initObj.hasOwnProperty('option')) {
        this.option = initObj.option
      }
      else {
        this.option = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveValueGoal
    // Serialize message field [comp]
    bufferOffset = _serializer.int32(obj.comp, buffer, bufferOffset);
    // Serialize message field [pose]
    bufferOffset = PoseData.serialize(obj.pose, buffer, bufferOffset);
    // Serialize message field [option]
    bufferOffset = _serializer.string(obj.option, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveValueGoal
    let len;
    let data = new MoveValueGoal(null);
    // Deserialize message field [comp]
    data.comp = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [pose]
    data.pose = PoseData.deserialize(buffer, bufferOffset);
    // Deserialize message field [option]
    data.option = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += PoseData.getMessageSize(object.pose);
    length += _getByteLength(object.option);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'denso_robot_core/MoveValueGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4e338683af37ba2d25d0bc83ee3893a2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32    comp
    PoseData pose
    string   option
    
    ================================================================================
    MSG: denso_robot_core/PoseData
    float32[] value
    int32     type
    int32     pass
    ExJoints  exjoints
    
    
    ================================================================================
    MSG: denso_robot_core/ExJoints
    int32    mode
    Joints[] joints
    
    
    ================================================================================
    MSG: denso_robot_core/Joints
    int32   joint
    float64 value
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveValueGoal(null);
    if (msg.comp !== undefined) {
      resolved.comp = msg.comp;
    }
    else {
      resolved.comp = 0
    }

    if (msg.pose !== undefined) {
      resolved.pose = PoseData.Resolve(msg.pose)
    }
    else {
      resolved.pose = new PoseData()
    }

    if (msg.option !== undefined) {
      resolved.option = msg.option;
    }
    else {
      resolved.option = ''
    }

    return resolved;
    }
};

module.exports = MoveValueGoal;
