// Generated by gencpp from file pcl_sensor_data/angleAdjustResponse.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_ANGLEADJUSTRESPONSE_H
#define PCL_SENSOR_DATA_MESSAGE_ANGLEADJUSTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_sensor_data
{
template <class ContainerAllocator>
struct angleAdjustResponse_
{
  typedef angleAdjustResponse_<ContainerAllocator> Type;

  angleAdjustResponse_()
    : angle(0.0)  {
    }
  angleAdjustResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> const> ConstPtr;

}; // struct angleAdjustResponse_

typedef ::pcl_sensor_data::angleAdjustResponse_<std::allocator<void> > angleAdjustResponse;

typedef boost::shared_ptr< ::pcl_sensor_data::angleAdjustResponse > angleAdjustResponsePtr;
typedef boost::shared_ptr< ::pcl_sensor_data::angleAdjustResponse const> angleAdjustResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pcl_sensor_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_sensor_data/angleAdjustResponse";
  }

  static const char* value(const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"float64 angle\n"
;
  }

  static const char* value(const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angleAdjustResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_sensor_data::angleAdjustResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_ANGLEADJUSTRESPONSE_H
