// Generated by gencpp from file pcl_sensor_data/angleAdjust.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_ANGLEADJUST_H
#define PCL_SENSOR_DATA_MESSAGE_ANGLEADJUST_H

#include <ros/service_traits.h>


#include <pcl_sensor_data/angleAdjustRequest.h>
#include <pcl_sensor_data/angleAdjustResponse.h>


namespace pcl_sensor_data
{

struct angleAdjust
{

typedef angleAdjustRequest Request;
typedef angleAdjustResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angleAdjust
} // namespace pcl_sensor_data


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_sensor_data::angleAdjust > {
  static const char* value()
  {
    return "f263ad018944d1f74b66bb892b6765bf";
  }

  static const char* value(const ::pcl_sensor_data::angleAdjust&) { return value(); }
};

template<>
struct DataType< ::pcl_sensor_data::angleAdjust > {
  static const char* value()
  {
    return "pcl_sensor_data/angleAdjust";
  }

  static const char* value(const ::pcl_sensor_data::angleAdjust&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_sensor_data::angleAdjustRequest> should match
// service_traits::MD5Sum< ::pcl_sensor_data::angleAdjust >
template<>
struct MD5Sum< ::pcl_sensor_data::angleAdjustRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::angleAdjust >::value();
  }
  static const char* value(const ::pcl_sensor_data::angleAdjustRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::angleAdjustRequest> should match
// service_traits::DataType< ::pcl_sensor_data::angleAdjust >
template<>
struct DataType< ::pcl_sensor_data::angleAdjustRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::angleAdjust >::value();
  }
  static const char* value(const ::pcl_sensor_data::angleAdjustRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_sensor_data::angleAdjustResponse> should match
// service_traits::MD5Sum< ::pcl_sensor_data::angleAdjust >
template<>
struct MD5Sum< ::pcl_sensor_data::angleAdjustResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::angleAdjust >::value();
  }
  static const char* value(const ::pcl_sensor_data::angleAdjustResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::angleAdjustResponse> should match
// service_traits::DataType< ::pcl_sensor_data::angleAdjust >
template<>
struct DataType< ::pcl_sensor_data::angleAdjustResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::angleAdjust >::value();
  }
  static const char* value(const ::pcl_sensor_data::angleAdjustResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_ANGLEADJUST_H
