// Generated by gencpp from file pcl_sensor_data/laserMaxResponse.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_LASERMAXRESPONSE_H
#define PCL_SENSOR_DATA_MESSAGE_LASERMAXRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_sensor_data
{
template <class ContainerAllocator>
struct laserMaxResponse_
{
  typedef laserMaxResponse_<ContainerAllocator> Type;

  laserMaxResponse_()
    : laserMax()  {
    }
  laserMaxResponse_(const ContainerAllocator& _alloc)
    : laserMax(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _laserMax_type;
  _laserMax_type laserMax;





  typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct laserMaxResponse_

typedef ::pcl_sensor_data::laserMaxResponse_<std::allocator<void> > laserMaxResponse;

typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxResponse > laserMaxResponsePtr;
typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxResponse const> laserMaxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator2> & rhs)
{
  return lhs.laserMax == rhs.laserMax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pcl_sensor_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13818a1733e356fc044787c07f28a3d1";
  }

  static const char* value(const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13818a1733e356fcULL;
  static const uint64_t static_value2 = 0x044787c07f28a3d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_sensor_data/laserMaxResponse";
  }

  static const char* value(const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"float64[] laserMax\n"
;
  }

  static const char* value(const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laserMax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct laserMaxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_sensor_data::laserMaxResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "laserMax: ";
    if (v.laserMax.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.laserMax.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.laserMax[i]);
    }
    if (v.laserMax.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_LASERMAXRESPONSE_H
