// Generated by gencpp from file pcl_sensor_data/laserMaxRequest.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_LASERMAXREQUEST_H
#define PCL_SENSOR_DATA_MESSAGE_LASERMAXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_sensor_data
{
template <class ContainerAllocator>
struct laserMaxRequest_
{
  typedef laserMaxRequest_<ContainerAllocator> Type;

  laserMaxRequest_()
    : req(false)  {
    }
  laserMaxRequest_(const ContainerAllocator& _alloc)
    : req(false)  {
  (void)_alloc;
    }



   typedef uint8_t _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct laserMaxRequest_

typedef ::pcl_sensor_data::laserMaxRequest_<std::allocator<void> > laserMaxRequest;

typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxRequest > laserMaxRequestPtr;
typedef boost::shared_ptr< ::pcl_sensor_data::laserMaxRequest const> laserMaxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req == rhs.req;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pcl_sensor_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be3c44e19d0c6b00b25e356c69155e2a";
  }

  static const char* value(const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe3c44e19d0c6b00ULL;
  static const uint64_t static_value2 = 0xb25e356c69155e2aULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_sensor_data/laserMaxRequest";
  }

  static const char* value(const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"bool req\n"
;
  }

  static const char* value(const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct laserMaxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_sensor_data::laserMaxRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "req: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_LASERMAXREQUEST_H
