// Generated by gencpp from file pcl_sensor_data/laserMax.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_LASERMAX_H
#define PCL_SENSOR_DATA_MESSAGE_LASERMAX_H

#include <ros/service_traits.h>


#include <pcl_sensor_data/laserMaxRequest.h>
#include <pcl_sensor_data/laserMaxResponse.h>


namespace pcl_sensor_data
{

struct laserMax
{

typedef laserMaxRequest Request;
typedef laserMaxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct laserMax
} // namespace pcl_sensor_data


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_sensor_data::laserMax > {
  static const char* value()
  {
    return "124fa1b43cf028c996c86f4d96158bb6";
  }

  static const char* value(const ::pcl_sensor_data::laserMax&) { return value(); }
};

template<>
struct DataType< ::pcl_sensor_data::laserMax > {
  static const char* value()
  {
    return "pcl_sensor_data/laserMax";
  }

  static const char* value(const ::pcl_sensor_data::laserMax&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_sensor_data::laserMaxRequest> should match
// service_traits::MD5Sum< ::pcl_sensor_data::laserMax >
template<>
struct MD5Sum< ::pcl_sensor_data::laserMaxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::laserMax >::value();
  }
  static const char* value(const ::pcl_sensor_data::laserMaxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::laserMaxRequest> should match
// service_traits::DataType< ::pcl_sensor_data::laserMax >
template<>
struct DataType< ::pcl_sensor_data::laserMaxRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::laserMax >::value();
  }
  static const char* value(const ::pcl_sensor_data::laserMaxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_sensor_data::laserMaxResponse> should match
// service_traits::MD5Sum< ::pcl_sensor_data::laserMax >
template<>
struct MD5Sum< ::pcl_sensor_data::laserMaxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::laserMax >::value();
  }
  static const char* value(const ::pcl_sensor_data::laserMaxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::laserMaxResponse> should match
// service_traits::DataType< ::pcl_sensor_data::laserMax >
template<>
struct DataType< ::pcl_sensor_data::laserMaxResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::laserMax >::value();
  }
  static const char* value(const ::pcl_sensor_data::laserMaxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_LASERMAX_H
