// Generated by gencpp from file pcl_sensor_data/ProcessPointcloudResponse.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_PROCESSPOINTCLOUDRESPONSE_H
#define PCL_SENSOR_DATA_MESSAGE_PROCESSPOINTCLOUDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_sensor_data
{
template <class ContainerAllocator>
struct ProcessPointcloudResponse_
{
  typedef ProcessPointcloudResponse_<ContainerAllocator> Type;

  ProcessPointcloudResponse_()
    : success(false)  {
    }
  ProcessPointcloudResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessPointcloudResponse_

typedef ::pcl_sensor_data::ProcessPointcloudResponse_<std::allocator<void> > ProcessPointcloudResponse;

typedef boost::shared_ptr< ::pcl_sensor_data::ProcessPointcloudResponse > ProcessPointcloudResponsePtr;
typedef boost::shared_ptr< ::pcl_sensor_data::ProcessPointcloudResponse const> ProcessPointcloudResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator1> & lhs, const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pcl_sensor_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_sensor_data/ProcessPointcloudResponse";
  }

  static const char* value(const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response\n"
"bool success\n"
;
  }

  static const char* value(const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessPointcloudResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_sensor_data::ProcessPointcloudResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_PROCESSPOINTCLOUDRESPONSE_H
