// Generated by gencpp from file pcl_sensor_data/ProcessPointcloud.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_PROCESSPOINTCLOUD_H
#define PCL_SENSOR_DATA_MESSAGE_PROCESSPOINTCLOUD_H

#include <ros/service_traits.h>


#include <pcl_sensor_data/ProcessPointcloudRequest.h>
#include <pcl_sensor_data/ProcessPointcloudResponse.h>


namespace pcl_sensor_data
{

struct ProcessPointcloud
{

typedef ProcessPointcloudRequest Request;
typedef ProcessPointcloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessPointcloud
} // namespace pcl_sensor_data


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_sensor_data::ProcessPointcloud > {
  static const char* value()
  {
    return "e188e0aaebb633ed14c21333921ef038";
  }

  static const char* value(const ::pcl_sensor_data::ProcessPointcloud&) { return value(); }
};

template<>
struct DataType< ::pcl_sensor_data::ProcessPointcloud > {
  static const char* value()
  {
    return "pcl_sensor_data/ProcessPointcloud";
  }

  static const char* value(const ::pcl_sensor_data::ProcessPointcloud&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_sensor_data::ProcessPointcloudRequest> should match
// service_traits::MD5Sum< ::pcl_sensor_data::ProcessPointcloud >
template<>
struct MD5Sum< ::pcl_sensor_data::ProcessPointcloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::ProcessPointcloud >::value();
  }
  static const char* value(const ::pcl_sensor_data::ProcessPointcloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::ProcessPointcloudRequest> should match
// service_traits::DataType< ::pcl_sensor_data::ProcessPointcloud >
template<>
struct DataType< ::pcl_sensor_data::ProcessPointcloudRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::ProcessPointcloud >::value();
  }
  static const char* value(const ::pcl_sensor_data::ProcessPointcloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_sensor_data::ProcessPointcloudResponse> should match
// service_traits::MD5Sum< ::pcl_sensor_data::ProcessPointcloud >
template<>
struct MD5Sum< ::pcl_sensor_data::ProcessPointcloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::ProcessPointcloud >::value();
  }
  static const char* value(const ::pcl_sensor_data::ProcessPointcloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::ProcessPointcloudResponse> should match
// service_traits::DataType< ::pcl_sensor_data::ProcessPointcloud >
template<>
struct DataType< ::pcl_sensor_data::ProcessPointcloudResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::ProcessPointcloud >::value();
  }
  static const char* value(const ::pcl_sensor_data::ProcessPointcloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_PROCESSPOINTCLOUD_H
