// Generated by gencpp from file pcl_sensor_data/StartRecording.msg
// DO NOT EDIT!


#ifndef PCL_SENSOR_DATA_MESSAGE_STARTRECORDING_H
#define PCL_SENSOR_DATA_MESSAGE_STARTRECORDING_H

#include <ros/service_traits.h>


#include <pcl_sensor_data/StartRecordingRequest.h>
#include <pcl_sensor_data/StartRecordingResponse.h>


namespace pcl_sensor_data
{

struct StartRecording
{

typedef StartRecordingRequest Request;
typedef StartRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartRecording
} // namespace pcl_sensor_data


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_sensor_data::StartRecording > {
  static const char* value()
  {
    return "e188e0aaebb633ed14c21333921ef038";
  }

  static const char* value(const ::pcl_sensor_data::StartRecording&) { return value(); }
};

template<>
struct DataType< ::pcl_sensor_data::StartRecording > {
  static const char* value()
  {
    return "pcl_sensor_data/StartRecording";
  }

  static const char* value(const ::pcl_sensor_data::StartRecording&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_sensor_data::StartRecordingRequest> should match
// service_traits::MD5Sum< ::pcl_sensor_data::StartRecording >
template<>
struct MD5Sum< ::pcl_sensor_data::StartRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::StartRecording >::value();
  }
  static const char* value(const ::pcl_sensor_data::StartRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::StartRecordingRequest> should match
// service_traits::DataType< ::pcl_sensor_data::StartRecording >
template<>
struct DataType< ::pcl_sensor_data::StartRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::StartRecording >::value();
  }
  static const char* value(const ::pcl_sensor_data::StartRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_sensor_data::StartRecordingResponse> should match
// service_traits::MD5Sum< ::pcl_sensor_data::StartRecording >
template<>
struct MD5Sum< ::pcl_sensor_data::StartRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_sensor_data::StartRecording >::value();
  }
  static const char* value(const ::pcl_sensor_data::StartRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_sensor_data::StartRecordingResponse> should match
// service_traits::DataType< ::pcl_sensor_data::StartRecording >
template<>
struct DataType< ::pcl_sensor_data::StartRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_sensor_data::StartRecording >::value();
  }
  static const char* value(const ::pcl_sensor_data::StartRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_SENSOR_DATA_MESSAGE_STARTRECORDING_H
