// Generated by gencpp from file add_post_pro_simulation/APPChangeHeight.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_APPCHANGEHEIGHT_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_APPCHANGEHEIGHT_H

#include <ros/service_traits.h>


#include <add_post_pro_simulation/APPChangeHeightRequest.h>
#include <add_post_pro_simulation/APPChangeHeightResponse.h>


namespace add_post_pro_simulation
{

struct APPChangeHeight
{

typedef APPChangeHeightRequest Request;
typedef APPChangeHeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct APPChangeHeight
} // namespace add_post_pro_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_post_pro_simulation::APPChangeHeight > {
  static const char* value()
  {
    return "84a8867fc8ccf3b6b9067181a42e5ae9";
  }

  static const char* value(const ::add_post_pro_simulation::APPChangeHeight&) { return value(); }
};

template<>
struct DataType< ::add_post_pro_simulation::APPChangeHeight > {
  static const char* value()
  {
    return "add_post_pro_simulation/APPChangeHeight";
  }

  static const char* value(const ::add_post_pro_simulation::APPChangeHeight&) { return value(); }
};


// service_traits::MD5Sum< ::add_post_pro_simulation::APPChangeHeightRequest> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPChangeHeight >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPChangeHeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPChangeHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPChangeHeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPChangeHeightRequest> should match
// service_traits::DataType< ::add_post_pro_simulation::APPChangeHeight >
template<>
struct DataType< ::add_post_pro_simulation::APPChangeHeightRequest>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPChangeHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPChangeHeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_post_pro_simulation::APPChangeHeightResponse> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPChangeHeight >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPChangeHeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPChangeHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPChangeHeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPChangeHeightResponse> should match
// service_traits::DataType< ::add_post_pro_simulation::APPChangeHeight >
template<>
struct DataType< ::add_post_pro_simulation::APPChangeHeightResponse>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPChangeHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPChangeHeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_APPCHANGEHEIGHT_H
