// Generated by gencpp from file add_post_pro_simulation/APPListModelsResponse.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_APPLISTMODELSRESPONSE_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_APPLISTMODELSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_post_pro_simulation
{
template <class ContainerAllocator>
struct APPListModelsResponse_
{
  typedef APPListModelsResponse_<ContainerAllocator> Type;

  APPListModelsResponse_()
    : models()  {
    }
  APPListModelsResponse_(const ContainerAllocator& _alloc)
    : models(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _models_type;
  _models_type models;





  typedef boost::shared_ptr< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct APPListModelsResponse_

typedef ::add_post_pro_simulation::APPListModelsResponse_<std::allocator<void> > APPListModelsResponse;

typedef boost::shared_ptr< ::add_post_pro_simulation::APPListModelsResponse > APPListModelsResponsePtr;
typedef boost::shared_ptr< ::add_post_pro_simulation::APPListModelsResponse const> APPListModelsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator1> & lhs, const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.models == rhs.models;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator1> & lhs, const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace add_post_pro_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68c1312e15cb67cd7b79f814607addf5";
  }

  static const char* value(const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68c1312e15cb67cdULL;
  static const uint64_t static_value2 = 0x7b79f814607addf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_post_pro_simulation/APPListModelsResponse";
  }

  static const char* value(const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] models\n"
;
  }

  static const char* value(const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.models);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct APPListModelsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_post_pro_simulation::APPListModelsResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "models: ";
    if (v.models.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.models.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.models[i]);
    }
    if (v.models.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_APPLISTMODELSRESPONSE_H
