// Generated by gencpp from file add_post_pro_simulation/APPSpawnModel.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNMODEL_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNMODEL_H

#include <ros/service_traits.h>


#include <add_post_pro_simulation/APPSpawnModelRequest.h>
#include <add_post_pro_simulation/APPSpawnModelResponse.h>


namespace add_post_pro_simulation
{

struct APPSpawnModel
{

typedef APPSpawnModelRequest Request;
typedef APPSpawnModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct APPSpawnModel
} // namespace add_post_pro_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnModel > {
  static const char* value()
  {
    return "6cdf43566fecf3a5e31bc8aac7b0f400";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnModel&) { return value(); }
};

template<>
struct DataType< ::add_post_pro_simulation::APPSpawnModel > {
  static const char* value()
  {
    return "add_post_pro_simulation/APPSpawnModel";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnModel&) { return value(); }
};


// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnModelRequest> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnModel >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPSpawnModel >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPSpawnModelRequest> should match
// service_traits::DataType< ::add_post_pro_simulation::APPSpawnModel >
template<>
struct DataType< ::add_post_pro_simulation::APPSpawnModelRequest>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPSpawnModel >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnModelResponse> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnModel >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPSpawnModel >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPSpawnModelResponse> should match
// service_traits::DataType< ::add_post_pro_simulation::APPSpawnModel >
template<>
struct DataType< ::add_post_pro_simulation::APPSpawnModelResponse>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPSpawnModel >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNMODEL_H
