// Generated by gencpp from file add_post_pro_simulation/APPSpawnDepowdering.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNDEPOWDERING_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNDEPOWDERING_H

#include <ros/service_traits.h>


#include <add_post_pro_simulation/APPSpawnDepowderingRequest.h>
#include <add_post_pro_simulation/APPSpawnDepowderingResponse.h>


namespace add_post_pro_simulation
{

struct APPSpawnDepowdering
{

typedef APPSpawnDepowderingRequest Request;
typedef APPSpawnDepowderingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct APPSpawnDepowdering
} // namespace add_post_pro_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnDepowdering > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnDepowdering&) { return value(); }
};

template<>
struct DataType< ::add_post_pro_simulation::APPSpawnDepowdering > {
  static const char* value()
  {
    return "add_post_pro_simulation/APPSpawnDepowdering";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnDepowdering&) { return value(); }
};


// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnDepowderingRequest> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnDepowdering >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnDepowderingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPSpawnDepowdering >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnDepowderingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPSpawnDepowderingRequest> should match
// service_traits::DataType< ::add_post_pro_simulation::APPSpawnDepowdering >
template<>
struct DataType< ::add_post_pro_simulation::APPSpawnDepowderingRequest>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPSpawnDepowdering >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnDepowderingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnDepowderingResponse> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnDepowdering >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnDepowderingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPSpawnDepowdering >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnDepowderingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPSpawnDepowderingResponse> should match
// service_traits::DataType< ::add_post_pro_simulation::APPSpawnDepowdering >
template<>
struct DataType< ::add_post_pro_simulation::APPSpawnDepowderingResponse>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPSpawnDepowdering >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnDepowderingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNDEPOWDERING_H
