// Generated by gencpp from file add_post_pro_simulation/APPSpawnCubeRequest.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNCUBEREQUEST_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNCUBEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_post_pro_simulation
{
template <class ContainerAllocator>
struct APPSpawnCubeRequest_
{
  typedef APPSpawnCubeRequest_<ContainerAllocator> Type;

  APPSpawnCubeRequest_()
    {
    }
  APPSpawnCubeRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct APPSpawnCubeRequest_

typedef ::add_post_pro_simulation::APPSpawnCubeRequest_<std::allocator<void> > APPSpawnCubeRequest;

typedef boost::shared_ptr< ::add_post_pro_simulation::APPSpawnCubeRequest > APPSpawnCubeRequestPtr;
typedef boost::shared_ptr< ::add_post_pro_simulation::APPSpawnCubeRequest const> APPSpawnCubeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace add_post_pro_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_post_pro_simulation/APPSpawnCubeRequest";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct APPSpawnCubeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::add_post_pro_simulation::APPSpawnCubeRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNCUBEREQUEST_H
