// Generated by gencpp from file add_post_pro_simulation/APPSpawnCube.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNCUBE_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNCUBE_H

#include <ros/service_traits.h>


#include <add_post_pro_simulation/APPSpawnCubeRequest.h>
#include <add_post_pro_simulation/APPSpawnCubeResponse.h>


namespace add_post_pro_simulation
{

struct APPSpawnCube
{

typedef APPSpawnCubeRequest Request;
typedef APPSpawnCubeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct APPSpawnCube
} // namespace add_post_pro_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnCube > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnCube&) { return value(); }
};

template<>
struct DataType< ::add_post_pro_simulation::APPSpawnCube > {
  static const char* value()
  {
    return "add_post_pro_simulation/APPSpawnCube";
  }

  static const char* value(const ::add_post_pro_simulation::APPSpawnCube&) { return value(); }
};


// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnCubeRequest> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnCube >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnCubeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPSpawnCube >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPSpawnCubeRequest> should match
// service_traits::DataType< ::add_post_pro_simulation::APPSpawnCube >
template<>
struct DataType< ::add_post_pro_simulation::APPSpawnCubeRequest>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPSpawnCube >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnCubeResponse> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::APPSpawnCube >
template<>
struct MD5Sum< ::add_post_pro_simulation::APPSpawnCubeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::APPSpawnCube >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::APPSpawnCubeResponse> should match
// service_traits::DataType< ::add_post_pro_simulation::APPSpawnCube >
template<>
struct DataType< ::add_post_pro_simulation::APPSpawnCubeResponse>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::APPSpawnCube >::value();
  }
  static const char* value(const ::add_post_pro_simulation::APPSpawnCubeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_APPSPAWNCUBE_H
