// Generated by gencpp from file add_post_pro_simulation/ConversionRequestRequest.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_CONVERSIONREQUESTREQUEST_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_CONVERSIONREQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_post_pro_simulation
{
template <class ContainerAllocator>
struct ConversionRequestRequest_
{
  typedef ConversionRequestRequest_<ContainerAllocator> Type;

  ConversionRequestRequest_()
    : name()  {
    }
  ConversionRequestRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConversionRequestRequest_

typedef ::add_post_pro_simulation::ConversionRequestRequest_<std::allocator<void> > ConversionRequestRequest;

typedef boost::shared_ptr< ::add_post_pro_simulation::ConversionRequestRequest > ConversionRequestRequestPtr;
typedef boost::shared_ptr< ::add_post_pro_simulation::ConversionRequestRequest const> ConversionRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator1> & lhs, const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator1> & lhs, const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace add_post_pro_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_post_pro_simulation/ConversionRequestRequest";
  }

  static const char* value(const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string name\n"
;
  }

  static const char* value(const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConversionRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_post_pro_simulation::ConversionRequestRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_CONVERSIONREQUESTREQUEST_H
