// Generated by gencpp from file add_post_pro_simulation/SurfaceHeight.msg
// DO NOT EDIT!


#ifndef ADD_POST_PRO_SIMULATION_MESSAGE_SURFACEHEIGHT_H
#define ADD_POST_PRO_SIMULATION_MESSAGE_SURFACEHEIGHT_H

#include <ros/service_traits.h>


#include <add_post_pro_simulation/SurfaceHeightRequest.h>
#include <add_post_pro_simulation/SurfaceHeightResponse.h>


namespace add_post_pro_simulation
{

struct SurfaceHeight
{

typedef SurfaceHeightRequest Request;
typedef SurfaceHeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SurfaceHeight
} // namespace add_post_pro_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_post_pro_simulation::SurfaceHeight > {
  static const char* value()
  {
    return "84a8867fc8ccf3b6b9067181a42e5ae9";
  }

  static const char* value(const ::add_post_pro_simulation::SurfaceHeight&) { return value(); }
};

template<>
struct DataType< ::add_post_pro_simulation::SurfaceHeight > {
  static const char* value()
  {
    return "add_post_pro_simulation/SurfaceHeight";
  }

  static const char* value(const ::add_post_pro_simulation::SurfaceHeight&) { return value(); }
};


// service_traits::MD5Sum< ::add_post_pro_simulation::SurfaceHeightRequest> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::SurfaceHeight >
template<>
struct MD5Sum< ::add_post_pro_simulation::SurfaceHeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::SurfaceHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::SurfaceHeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::SurfaceHeightRequest> should match
// service_traits::DataType< ::add_post_pro_simulation::SurfaceHeight >
template<>
struct DataType< ::add_post_pro_simulation::SurfaceHeightRequest>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::SurfaceHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::SurfaceHeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_post_pro_simulation::SurfaceHeightResponse> should match
// service_traits::MD5Sum< ::add_post_pro_simulation::SurfaceHeight >
template<>
struct MD5Sum< ::add_post_pro_simulation::SurfaceHeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_post_pro_simulation::SurfaceHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::SurfaceHeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_post_pro_simulation::SurfaceHeightResponse> should match
// service_traits::DataType< ::add_post_pro_simulation::SurfaceHeight >
template<>
struct DataType< ::add_post_pro_simulation::SurfaceHeightResponse>
{
  static const char* value()
  {
    return DataType< ::add_post_pro_simulation::SurfaceHeight >::value();
  }
  static const char* value(const ::add_post_pro_simulation::SurfaceHeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_POST_PRO_SIMULATION_MESSAGE_SURFACEHEIGHT_H
