// Generated by gencpp from file realsense_cam/FetchOnePointCloudRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUDREQUEST_H
#define REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_cam
{
template <class ContainerAllocator>
struct FetchOnePointCloudRequest_
{
  typedef FetchOnePointCloudRequest_<ContainerAllocator> Type;

  FetchOnePointCloudRequest_()
    {
    }
  FetchOnePointCloudRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FetchOnePointCloudRequest_

typedef ::realsense_cam::FetchOnePointCloudRequest_<std::allocator<void> > FetchOnePointCloudRequest;

typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudRequest > FetchOnePointCloudRequestPtr;
typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudRequest const> FetchOnePointCloudRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace realsense_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_cam/FetchOnePointCloudRequest";
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FetchOnePointCloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::realsense_cam::FetchOnePointCloudRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUDREQUEST_H
