// Generated by gencpp from file realsense_cam/FetchOnePointCloudResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUDRESPONSE_H
#define REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace realsense_cam
{
template <class ContainerAllocator>
struct FetchOnePointCloudResponse_
{
  typedef FetchOnePointCloudResponse_<ContainerAllocator> Type;

  FetchOnePointCloudResponse_()
    : success(false)
    , reason()
    , pointcloud()  {
    }
  FetchOnePointCloudResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , reason(_alloc)
    , pointcloud(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;





  typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FetchOnePointCloudResponse_

typedef ::realsense_cam::FetchOnePointCloudResponse_<std::allocator<void> > FetchOnePointCloudResponse;

typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudResponse > FetchOnePointCloudResponsePtr;
typedef boost::shared_ptr< ::realsense_cam::FetchOnePointCloudResponse const> FetchOnePointCloudResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator1> & lhs, const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.reason == rhs.reason &&
    lhs.pointcloud == rhs.pointcloud;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator1> & lhs, const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12debe1ff97e2a037af192b4cc727ffc";
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12debe1ff97e2a03ULL;
  static const uint64_t static_value2 = 0x7af192b4cc727ffcULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_cam/FetchOnePointCloudResponse";
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Success: TRUE if frame is successfully delivered.\n"
"# Reason: detail of error if not succeeded.\n"
"bool success\n"
"string reason \n"
"sensor_msgs/PointCloud2 pointcloud\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.reason);
      stream.next(m.pointcloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FetchOnePointCloudResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_cam::FetchOnePointCloudResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pointcloud: ";
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUDRESPONSE_H
