// Generated by gencpp from file realsense_cam/FetchOneRGB.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_FETCHONERGB_H
#define REALSENSE_CAM_MESSAGE_FETCHONERGB_H

#include <ros/service_traits.h>


#include <realsense_cam/FetchOneRGBRequest.h>
#include <realsense_cam/FetchOneRGBResponse.h>


namespace realsense_cam
{

struct FetchOneRGB
{

typedef FetchOneRGBRequest Request;
typedef FetchOneRGBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FetchOneRGB
} // namespace realsense_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_cam::FetchOneRGB > {
  static const char* value()
  {
    return "ccd168e371de7ed9bbb3078068a6b679";
  }

  static const char* value(const ::realsense_cam::FetchOneRGB&) { return value(); }
};

template<>
struct DataType< ::realsense_cam::FetchOneRGB > {
  static const char* value()
  {
    return "realsense_cam/FetchOneRGB";
  }

  static const char* value(const ::realsense_cam::FetchOneRGB&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_cam::FetchOneRGBRequest> should match
// service_traits::MD5Sum< ::realsense_cam::FetchOneRGB >
template<>
struct MD5Sum< ::realsense_cam::FetchOneRGBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::FetchOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneRGBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::FetchOneRGBRequest> should match
// service_traits::DataType< ::realsense_cam::FetchOneRGB >
template<>
struct DataType< ::realsense_cam::FetchOneRGBRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::FetchOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneRGBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_cam::FetchOneRGBResponse> should match
// service_traits::MD5Sum< ::realsense_cam::FetchOneRGB >
template<>
struct MD5Sum< ::realsense_cam::FetchOneRGBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::FetchOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneRGBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::FetchOneRGBResponse> should match
// service_traits::DataType< ::realsense_cam::FetchOneRGB >
template<>
struct DataType< ::realsense_cam::FetchOneRGBResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::FetchOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneRGBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_FETCHONERGB_H
