// Generated by gencpp from file realsense_cam/FetchOnePointCloud.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUD_H
#define REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUD_H

#include <ros/service_traits.h>


#include <realsense_cam/FetchOnePointCloudRequest.h>
#include <realsense_cam/FetchOnePointCloudResponse.h>


namespace realsense_cam
{

struct FetchOnePointCloud
{

typedef FetchOnePointCloudRequest Request;
typedef FetchOnePointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FetchOnePointCloud
} // namespace realsense_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_cam::FetchOnePointCloud > {
  static const char* value()
  {
    return "12debe1ff97e2a037af192b4cc727ffc";
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloud&) { return value(); }
};

template<>
struct DataType< ::realsense_cam::FetchOnePointCloud > {
  static const char* value()
  {
    return "realsense_cam/FetchOnePointCloud";
  }

  static const char* value(const ::realsense_cam::FetchOnePointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_cam::FetchOnePointCloudRequest> should match
// service_traits::MD5Sum< ::realsense_cam::FetchOnePointCloud >
template<>
struct MD5Sum< ::realsense_cam::FetchOnePointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::FetchOnePointCloud >::value();
  }
  static const char* value(const ::realsense_cam::FetchOnePointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::FetchOnePointCloudRequest> should match
// service_traits::DataType< ::realsense_cam::FetchOnePointCloud >
template<>
struct DataType< ::realsense_cam::FetchOnePointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::FetchOnePointCloud >::value();
  }
  static const char* value(const ::realsense_cam::FetchOnePointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_cam::FetchOnePointCloudResponse> should match
// service_traits::MD5Sum< ::realsense_cam::FetchOnePointCloud >
template<>
struct MD5Sum< ::realsense_cam::FetchOnePointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::FetchOnePointCloud >::value();
  }
  static const char* value(const ::realsense_cam::FetchOnePointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::FetchOnePointCloudResponse> should match
// service_traits::DataType< ::realsense_cam::FetchOnePointCloud >
template<>
struct DataType< ::realsense_cam::FetchOnePointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::FetchOnePointCloud >::value();
  }
  static const char* value(const ::realsense_cam::FetchOnePointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_FETCHONEPOINTCLOUD_H
