// Generated by gencpp from file realsense_cam/FetchOneDepth.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_FETCHONEDEPTH_H
#define REALSENSE_CAM_MESSAGE_FETCHONEDEPTH_H

#include <ros/service_traits.h>


#include <realsense_cam/FetchOneDepthRequest.h>
#include <realsense_cam/FetchOneDepthResponse.h>


namespace realsense_cam
{

struct FetchOneDepth
{

typedef FetchOneDepthRequest Request;
typedef FetchOneDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FetchOneDepth
} // namespace realsense_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_cam::FetchOneDepth > {
  static const char* value()
  {
    return "8f1bfbb7170049fa0e75d292e4ff7bed";
  }

  static const char* value(const ::realsense_cam::FetchOneDepth&) { return value(); }
};

template<>
struct DataType< ::realsense_cam::FetchOneDepth > {
  static const char* value()
  {
    return "realsense_cam/FetchOneDepth";
  }

  static const char* value(const ::realsense_cam::FetchOneDepth&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_cam::FetchOneDepthRequest> should match
// service_traits::MD5Sum< ::realsense_cam::FetchOneDepth >
template<>
struct MD5Sum< ::realsense_cam::FetchOneDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::FetchOneDepth >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::FetchOneDepthRequest> should match
// service_traits::DataType< ::realsense_cam::FetchOneDepth >
template<>
struct DataType< ::realsense_cam::FetchOneDepthRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::FetchOneDepth >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_cam::FetchOneDepthResponse> should match
// service_traits::MD5Sum< ::realsense_cam::FetchOneDepth >
template<>
struct MD5Sum< ::realsense_cam::FetchOneDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::FetchOneDepth >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::FetchOneDepthResponse> should match
// service_traits::DataType< ::realsense_cam::FetchOneDepth >
template<>
struct DataType< ::realsense_cam::FetchOneDepthResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::FetchOneDepth >::value();
  }
  static const char* value(const ::realsense_cam::FetchOneDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_FETCHONEDEPTH_H
