// Generated by gencpp from file realsense_cam/SaveOneRGBResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_SAVEONERGBRESPONSE_H
#define REALSENSE_CAM_MESSAGE_SAVEONERGBRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_cam
{
template <class ContainerAllocator>
struct SaveOneRGBResponse_
{
  typedef SaveOneRGBResponse_<ContainerAllocator> Type;

  SaveOneRGBResponse_()
    : success(false)  {
    }
  SaveOneRGBResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveOneRGBResponse_

typedef ::realsense_cam::SaveOneRGBResponse_<std::allocator<void> > SaveOneRGBResponse;

typedef boost::shared_ptr< ::realsense_cam::SaveOneRGBResponse > SaveOneRGBResponsePtr;
typedef boost::shared_ptr< ::realsense_cam::SaveOneRGBResponse const> SaveOneRGBResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator1> & lhs, const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator1> & lhs, const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_cam/SaveOneRGBResponse";
  }

  static const char* value(const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Success: TRUE if frame is successfully delivered.\n"
"bool success\n"
;
  }

  static const char* value(const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveOneRGBResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_cam::SaveOneRGBResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_SAVEONERGBRESPONSE_H
