// Generated by gencpp from file realsense_cam/SaveOneRGB.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_SAVEONERGB_H
#define REALSENSE_CAM_MESSAGE_SAVEONERGB_H

#include <ros/service_traits.h>


#include <realsense_cam/SaveOneRGBRequest.h>
#include <realsense_cam/SaveOneRGBResponse.h>


namespace realsense_cam
{

struct SaveOneRGB
{

typedef SaveOneRGBRequest Request;
typedef SaveOneRGBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveOneRGB
} // namespace realsense_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_cam::SaveOneRGB > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::realsense_cam::SaveOneRGB&) { return value(); }
};

template<>
struct DataType< ::realsense_cam::SaveOneRGB > {
  static const char* value()
  {
    return "realsense_cam/SaveOneRGB";
  }

  static const char* value(const ::realsense_cam::SaveOneRGB&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_cam::SaveOneRGBRequest> should match
// service_traits::MD5Sum< ::realsense_cam::SaveOneRGB >
template<>
struct MD5Sum< ::realsense_cam::SaveOneRGBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::SaveOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::SaveOneRGBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::SaveOneRGBRequest> should match
// service_traits::DataType< ::realsense_cam::SaveOneRGB >
template<>
struct DataType< ::realsense_cam::SaveOneRGBRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::SaveOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::SaveOneRGBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_cam::SaveOneRGBResponse> should match
// service_traits::MD5Sum< ::realsense_cam::SaveOneRGB >
template<>
struct MD5Sum< ::realsense_cam::SaveOneRGBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::SaveOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::SaveOneRGBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::SaveOneRGBResponse> should match
// service_traits::DataType< ::realsense_cam::SaveOneRGB >
template<>
struct DataType< ::realsense_cam::SaveOneRGBResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::SaveOneRGB >::value();
  }
  static const char* value(const ::realsense_cam::SaveOneRGBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_SAVEONERGB_H
