// Generated by gencpp from file realsense_cam/SaveOnePCL.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAM_MESSAGE_SAVEONEPCL_H
#define REALSENSE_CAM_MESSAGE_SAVEONEPCL_H

#include <ros/service_traits.h>


#include <realsense_cam/SaveOnePCLRequest.h>
#include <realsense_cam/SaveOnePCLResponse.h>


namespace realsense_cam
{

struct SaveOnePCL
{

typedef SaveOnePCLRequest Request;
typedef SaveOnePCLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveOnePCL
} // namespace realsense_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_cam::SaveOnePCL > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::realsense_cam::SaveOnePCL&) { return value(); }
};

template<>
struct DataType< ::realsense_cam::SaveOnePCL > {
  static const char* value()
  {
    return "realsense_cam/SaveOnePCL";
  }

  static const char* value(const ::realsense_cam::SaveOnePCL&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_cam::SaveOnePCLRequest> should match
// service_traits::MD5Sum< ::realsense_cam::SaveOnePCL >
template<>
struct MD5Sum< ::realsense_cam::SaveOnePCLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::SaveOnePCL >::value();
  }
  static const char* value(const ::realsense_cam::SaveOnePCLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::SaveOnePCLRequest> should match
// service_traits::DataType< ::realsense_cam::SaveOnePCL >
template<>
struct DataType< ::realsense_cam::SaveOnePCLRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::SaveOnePCL >::value();
  }
  static const char* value(const ::realsense_cam::SaveOnePCLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_cam::SaveOnePCLResponse> should match
// service_traits::MD5Sum< ::realsense_cam::SaveOnePCL >
template<>
struct MD5Sum< ::realsense_cam::SaveOnePCLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_cam::SaveOnePCL >::value();
  }
  static const char* value(const ::realsense_cam::SaveOnePCLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_cam::SaveOnePCLResponse> should match
// service_traits::DataType< ::realsense_cam::SaveOnePCL >
template<>
struct DataType< ::realsense_cam::SaveOnePCLResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_cam::SaveOnePCL >::value();
  }
  static const char* value(const ::realsense_cam::SaveOnePCLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAM_MESSAGE_SAVEONEPCL_H
