controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_eef_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: laser_test_default